#ifndef HEADERS_AUDIO_H
#define HEADERS_AUDIO_H

/* Declarations for audio.c: background music track playback (the
 * MOD-tracker-based \SOUND\uwNN.mod player). Pulls in uw.h itself so
 * this header is self-contained for any caller. */
#include "uw.h"

/* Opens the real SDL2 audio device + vendored HxCModPlayer backend (see
 * audio.c's "Real MOD playback backend" block comment). Call once, early
 * at startup, right after SDL_Init(... | SDL_INIT_AUDIO) and before any
 * play_music_track call. */
void init_music_playback_subsystem(void);

undefined4 reset_dialogue_speech_state();
void clear_ambient_sound_target_thunk();
undefined2 load_voice_sample_page();
uint read_voice_sample_page_chunk();
void cache_ambient_sound_handle();
undefined4 acquire_sound_resource_slot();
void release_sound_resource_slot();
undefined4 init_sound_channel_slot();
void release_sound_channel_slot();
undefined4 load_and_resample_wave_sample();
undefined4 load_and_resample_wave_file();
undefined1 *construct_and_load_mod_player();
undefined4 destroy_mod_player();
void reset_mod_player_state();
undefined4 start_mod_player_playback();
undefined4 stop_mod_player_playback();
bool queue_mod_audio_buffer();
void process_mod_tracker_row();
undefined4 mix_mod_channels_to_buffer();
void apply_mod_tracker_tick_effects();
void mod_player_wave_out_callback();
void adjust_mod_channel_volume();
void apply_mod_tone_portamento();
void apply_mod_vibrato_effect();
void apply_mod_tremolo_effect();
void build_mod_volume_sample_table();
int read_mod_word_length_field();
bool arm_sfx_trigger_slot();
undefined4 start_sfx_trigger_slot();
undefined4 stop_sfx_trigger_slot();
void register_sound_channel_pool_cleanup();
void init_all_sound_channel_slots();
void release_all_sound_channel_slots();
undefined1 is_sfx_trigger_slot_active();
void resize_mod_event_row_array();
void resize_mod_pattern_row_array();
void init_mod_dynamic_array();
void resize_mod_int_array();
void destroy_mod_dynamic_array();
undefined1 *reset_mod_dynamic_array_and_maybe_free();
void serialize_mod_int_array();
void init_mod_pattern_array();
void resize_mod_pattern_array();
void destroy_mod_pattern_array();
void serialize_mod_pattern_array();
void init_mod_instrument_array();
void resize_mod_instrument_array();
void destroy_mod_instrument_array();
void serialize_mod_instrument_array();
void init_mod_channel_state_array();
void resize_mod_channel_state_array();
void destroy_mod_channel_state_array();
void serialize_mod_channel_state_array();
undefined4 destroy_mod_dynamic_array_and_maybe_free();
undefined4 destroy_mod_pattern_array_and_maybe_free();
undefined4 destroy_mod_instrument_array_and_maybe_free();
undefined4 destroy_mod_channel_state_array_and_maybe_free();
void construct_mod_event_array_range();
void destroy_mod_row_array_range();
void destroy_mod_row_array_elem();
void serialize_mod_event_row_array();
undefined4 destroy_mod_row_array_elem_and_maybe_free();
void write_mod_event_array();
void construct_mod_row_array_range();
void construct_mod_int_array_range();
void destroy_mod_pattern_array_range();
void destroy_mod_pattern_array_elem();
void serialize_mod_pattern_row_array();
undefined4 destroy_mod_pattern_array_elem_and_maybe_free();
void write_mod_pattern_row_array();
void construct_mod_pattern_array_range();
void write_mod_pattern_array();
void destroy_mod_instrument_array_range();
void construct_mod_instrument_array_range();
void write_mod_instrument_array();
void construct_mod_channel_state_array_range();
void construct_mod_row_array_elem();
void construct_mod_pattern_array_elem();
undefined4 play_music_track();
void resume_music_playback();
undefined1 get_current_music_track();
undefined4 is_music_playing();
undefined4 is_sound_effects_enabled();
void set_music_enabled();
void set_sound_effects_enabled();
void stop_current_audio_handle();
undefined4 play_positional_sound_effect();
undefined4 play_sound_effect_with_pan();
undefined4 play_sound_effect_at_object();
void stop_movement_sound_handle();
void stop_current_audio_handle_dup();
uint allocate_and_play_sound_channel();
void trigger_sound_sample_note();
void play_musical_instrument();
undefined4 check_secret_tune_match();
void shutdown_sound_effects();
void shutdown_music_module();
void set_pending_music_track();
void pick_random_pending_music_track();
void advance_menu_music_track();
void update_ingame_music_track();
bool advance_menu_music_track_elapsed();
undefined4 get_audio_subsystem_flag();
undefined4 audio_always_true_stub();
undefined4 play_numbered_voice_sample();
void voice_sample_cluster_stub_1();
bool is_voice_sample_finished();
void stop_voice_sample();
void voice_sample_cluster_stub_2();
void start_ambient_sound_effect();
void stop_ambient_sound_effect();
void init_ambient_sound_timing();
void clear_ambient_sound_target();

#endif
