/* Table of every runtime option: X(type, field, default, help). Included by options.h/options.c.
   Option NAME is set with --name-with-dashes[=value] (field with _ -> -), or the legacy env var
   UW_NAME. Types: BOOL (--x, --x=1/0, --no-x), INT, FLOAT, STR. */
X(BOOL, always_show_cursor, 1, "Always draw the mouse cursor (--always-show-cursor=0 hides it unless the game shows it).")
X(INT, ambient_bias_reduction, UW_OPT_UNSET, "Calibration added to the ambient light bias (negative brightens). Unset keeps the built-in value.")
X(STR, audio_mode, NULL, "Audio source: \"dos\" (DOS music+effects), \"hybrid\", or unset for the converted Pocket PC audio.")
X(FLOAT, brightness, 1.0f, "Palette brightness multiplier; the Pocket PC build used 1.5, DOS 1.0.")
X(BOOL, debug, 0, "Print the player's position: at new-character spawn, and whenever it or the view angle changes.")
X(BOOL, container_autoclose_on_drag_out, 0, "Close an open container when its last item is dragged out.")
X(STR, data_dir, NULL, "Directory holding the game data files (the DATA/, CUTS/, CRIT/ folders). Required.")
X(INT, decal_push, UW_OPT_UNSET, "Decal push-out magnitude (calibration).")
X(INT, decal_push_sign, 1, "Decal push-out sign (calibration).")
X(INT, demo_delay_ms, UW_OPT_UNSET, "Milliseconds between demo script lines (0 = one per pump).")
X(STR, demo_file, NULL, "Play back this demo script (see the demo_*.txt files).")
X(BOOL, demo_keep_running, 0, "Keep the game running after the demo script ends.")
X(BOOL, diag_sprlist, 0, "Diagnostics: sprlist.")
X(BOOL, diag_text, 0, "Diagnostics: text.")
X(BOOL, debug_pick_view, 0, "Paint the per-pixel object-pick buffer over the 3D viewport (also a toggle in the debug panel).")
X(BOOL, disable_3d_geometry, 0, "Disable 3d geometry.")
X(BOOL, disable_3d_objects, 0, "Disable 3d objects.")
X(BOOL, disable_pick_rerender, 0, "Disable pick rerender.")
X(BOOL, disable_tile_features, 0, "Disable tile features.")
X(BOOL, dither, 1, "Ordered dithering of dungeon lighting (--dither=0 disables).")
X(STR, dos_data_dir, NULL, "Directory of the DOS version's data, used by --audio-mode=dos|hybrid for its music and effects.")
X(INT, dos_music_volume, 80, "DOS music volume, 0-100.")
X(BOOL, dump_all_objects, 0, "Debug: dump all objects.")
X(STR, dump_containers_file, NULL, "File the container census is written to.")
X(STR, dump_critter_sheet, NULL, "Comma list of critter types to dump as sprite sheets.")
X(INT, dump_critter_sheet_maxdir, 63, "Highest direction swept by --dump-critter-sheet.")
X(INT, dump_critter_sheet_maxframe, 15, "Highest frame swept by --dump-critter-sheet.")
X(BOOL, dump_model_raw, 0, "Debug: dump model raw.")
X(BOOL, dump_names, 0, "Debug: dump names.")
X(BOOL, dump_objects, 0, "Debug: dump objects.")
X(STR, dump_objects_file, NULL, "File the --dump-objects census is written to.")
X(STR, dump_sprite_dir, NULL, "Directory sprite dumps are written to.")
X(STR, dump_sprite_frames, NULL, "Frame ids/ranges (\"5,10-20\") to dump as standalone sprite images.")
X(STR, dump_sprite_ids, NULL, "Object-sprite ids/ranges to dump as standalone sprite images.")
X(BOOL, fast_sleep, 0, "Make Sleep() return immediately (used by the regression runner).")
X(INT, force_critter_frame, UW_OPT_UNSET, "Force every critter to this animation frame.")
X(INT, force_critter_state, UW_OPT_UNSET, "Force every critter into this animation state.")
X(BOOL, extralights, 0, "Add small distance lights around campfires, glowing rocks, lit torches and magic projectiles (up to 8 at once).")
X(BOOL, fullbright, 1, "Skip the ARM distance falloff for palette indices LIGHT.DAT leaves fullbright (lava, magic).")
X(INT, hack_pitch, UW_OPT_UNSET, "Force the camera pitch (0-360).")
X(BOOL, hack_reveal_depth, 0, "Hack reveal depth.")
X(BOOL, hack_reveal_depth_zero, 0, "Hack reveal depth zero.")
X(STR, light_mode, NULL, "Lighting: \"dos\" uses LIGHT.DAT/SHADES.DAT shade tables; unset/\"arm\" keeps the Pocket PC RGB falloff.")
X(INT, look_slot, UW_OPT_UNSET, "Dump object-slot details for this slot once.")
X(BOOL, model_no_depth_sort, 0, "Model no depth sort.")
X(BOOL, no_force_3d_redraw, 0, "Do not force 3d redraw every pass.")
X(BOOL, no_force_cursor_redraw, 0, "Do not force cursor redraw every pass.")
X(BOOL, no_force_swing_tick, 0, "Do not force swing tick every pass.")
X(INT, palette_cycle_ms, 250, "Milliseconds per water/lava palette-cycle step (0 disables the cycling).")
X(BOOL, pick_diag, 0, "Pick diag.")
X(INT, pick_force_slot, UW_OPT_UNSET, "Force the object-pick pass to this slot.")
X(BOOL, player_no_bounce, 1, "Clear the player's downward velocity on landing (--player-no-bounce=0 restores the bounce).")
X(INT, record_delay_ms, UW_OPT_UNSET, "DELAY line written into a recorded demo file.")
X(STR, record_demofile, NULL, "Record input to this demo script file.")
X(BOOL, touchscreen, 0, "Use the full-height touchscreen window layout.")
X(INT, turn_accel, 0x60, "Turn acceleration used for keyboard turning.")
X(INT, walk_accel, 0x30, "Walk acceleration used for keyboard movement.")
