/* Table of every runtime option: X(type, field, default, help). Included by options.h/options.c.
   Option NAME is set with --name-with-dashes[=value] (field with _ -> -), or the legacy env var
   UW_NAME. Types: BOOL (--x, --x=1/0, --no-x), INT, FLOAT, STR. */
X(BOOL, always_show_cursor, 1, "Always draw the mouse cursor (--always-show-cursor=0 hides it unless the game shows it).")
X(INT, ambient_bias_reduction, UW_OPT_UNSET, "Calibration added to the ambient light bias (negative brightens). Unset keeps the built-in value.")
X(STR, audio_mode, NULL, "Audio source: \"dos\" (DOS music+effects), \"hybrid\", or unset for the converted Pocket PC audio.")
X(FLOAT, brightness, 1.0f, "Palette brightness multiplier; the Pocket PC build used 1.5, DOS 1.0.")
X(BOOL, container_autoclose_on_drag_out, 0, "Close an open container when its last item is dragged out.")
X(STR, data_dir, NULL, "Directory holding the game data files (the DATA/, CUTS/, CRIT/ folders). Required.")
X(BOOL, debug_ambient, 0, "Debug trace: ambient.")
X(BOOL, debug_armor_tables, 0, "Debug trace: armor tables.")
X(BOOL, debug_audio, 0, "Debug trace: audio.")
X(BOOL, debug_automap_cursor, 0, "Debug trace: automap cursor.")
X(BOOL, debug_automap_note, 0, "Debug trace: automap note.")
X(BOOL, debug_automap_reveal, 0, "Debug trace: automap reveal.")
X(BOOL, debug_auto_farewell, 0, "Debug trace: auto farewell.")
X(INT, debug_auto_pick, UW_OPT_UNSET, "Conversation test hook: pick this reply when a conversation auto-answers.")
X(BOOL, debug_babl, 0, "Debug trace: babl.")
X(BOOL, debug_bag_trace, 0, "Debug trace: bag trace.")
X(BOOL, debug_blitraw, 0, "Debug trace: blitraw.")
X(BOOL, debug_clickregion, 0, "Debug trace: clickregion.")
X(BOOL, debug_combat, 0, "Debug trace: combat.")
X(BOOL, debug_compass, 0, "Debug trace: compass.")
X(BOOL, debug_critter, 0, "Debug trace: critter.")
X(BOOL, debug_critter_name, 0, "Debug trace: critter name.")
X(BOOL, debug_critter_tablespan, 0, "Debug trace: critter tablespan.")
X(BOOL, debug_critter_z, 0, "Debug trace: critter z.")
X(BOOL, debug_cursorclick, 0, "Debug trace: cursorclick.")
X(BOOL, debug_cursorclip, 0, "Debug trace: cursorclip.")
X(BOOL, debug_cursorerase, 0, "Debug trace: cursorerase.")
X(BOOL, debug_cursorshow, 0, "Debug trace: cursorshow.")
X(BOOL, debug_dbgui, 0, "Debug trace: dbgui.")
X(BOOL, debug_door, 0, "Debug trace: door.")
X(BOOL, debug_door2, 0, "Debug trace: door2.")
X(BOOL, debug_door_pos, 0, "Debug trace: door pos.")
X(BOOL, debug_dragon, 0, "Debug trace: dragon.")
X(BOOL, debug_draw, 0, "Debug trace: draw.")
X(INT, debug_draw_every, 1, "With --debug-draw, write only every Nth draw dump.")
X(BOOL, debug_draw_inv_positions, 0, "Debug trace: draw inv positions.")
X(BOOL, debug_dump_conv_strings, 0, "Debug: dump conv strings to files.")
X(BOOL, debug_dump_crit, 0, "Debug: dump crit to files.")
X(BOOL, debug_dump_crit_all, 0, "Debug: dump crit all to files.")
X(BOOL, debug_dump_crit_pal, 0, "Debug: dump crit pal to files.")
X(BOOL, debug_dump_gr, 0, "Debug: dump gr to files.")
X(BOOL, debug_dump_revealmap, 0, "Debug: dump revealmap to files.")
X(BOOL, debug_dump_tmap, 0, "Debug: dump tmap to files.")
X(BOOL, debug_enddraw, 0, "Debug trace: enddraw.")
X(BOOL, debug_eparse, 0, "Debug trace: eparse.")
X(BOOL, debug_eyeheight, 0, "Debug trace: eyeheight.")
X(BOOL, debug_face51, 0, "Debug trace: face51.")
X(BOOL, debug_floorz, 0, "Debug trace: floorz.")
X(BOOL, debug_flushcaller, 0, "Debug trace: flushcaller.")
X(BOOL, debug_flushgate, 0, "Debug trace: flushgate.")
X(STR, debug_force_item_id, NULL, "Hex object id written over backpack slot 12 once (paper-doll test hook).")
X(BOOL, debug_force_quest_test, 0, "Debug trace: force quest test.")
X(BOOL, debug_geometry_dist, 0, "Debug trace: geometry dist.")
X(BOOL, debug_hudsplit, 0, "Debug trace: hudsplit.")
X(BOOL, debug_inputevent, 0, "Debug trace: inputevent.")
X(BOOL, debug_inputevent2, 0, "Debug trace: inputevent2.")
X(BOOL, debug_inv, 0, "Debug trace: inv.")
X(BOOL, debug_itersplit, 0, "Debug trace: itersplit.")
X(BOOL, debug_jump, 0, "Debug trace: jump.")
X(BOOL, debug_jump2, 0, "Debug trace: jump2.")
X(STR, debug_level, NULL, "Minimum log level: TRACE, INFO, WARN or ERR.")
X(BOOL, debug_loco, 0, "Debug trace: loco.")
X(BOOL, debug_loot, 0, "Debug trace: loot.")
X(BOOL, debug_mantra, 0, "Debug trace: mantra.")
X(BOOL, debug_modebtn, 0, "Debug trace: modebtn.")
X(BOOL, debug_modeicon, 0, "Debug trace: modeicon.")
X(BOOL, debug_model, 0, "Debug trace: model.")
X(BOOL, debug_model_parse_hwm, 0, "Debug trace: model parse hwm.")
X(BOOL, debug_model_tokens, 0, "Debug trace: model tokens.")
X(BOOL, debug_movepace, 0, "Debug trace: movepace.")
X(STR, debug_nearclip_range, NULL, "\"lo:hi\" record range for near-clip tracing.")
X(BOOL, debug_npc_attitude, 0, "Debug trace: npc attitude.")
X(BOOL, debug_npc_gate, 0, "Debug trace: npc gate.")
X(BOOL, debug_npc_goal_switch, 0, "Debug trace: npc goal switch.")
X(BOOL, debug_npc_move, 0, "Debug trace: npc move.")
X(BOOL, debug_npc_phase, 0, "Debug trace: npc phase.")
X(BOOL, debug_npc_pos, 0, "Debug trace: npc pos.")
X(BOOL, debug_npc_speed, 0, "Debug trace: npc speed.")
X(BOOL, debug_npc_state, 0, "Debug trace: npc state.")
X(BOOL, debug_npc_statemachine, 0, "Debug trace: npc statemachine.")
X(BOOL, debug_npc_tick, 0, "Debug trace: npc tick.")
X(BOOL, debug_npc_wander, 0, "Debug trace: npc wander.")
X(BOOL, debug_objclass, 0, "Debug trace: objclass.")
X(BOOL, debug_objpos, 0, "Debug trace: objpos.")
X(BOOL, debug_opcode_trace, 0, "Debug trace: opcode trace.")
X(BOOL, debug_palcycle, 0, "Debug trace: palcycle.")
X(BOOL, debug_palcycle_records, 0, "Debug trace: palcycle records.")
X(BOOL, debug_pausemenu, 0, "Debug trace: pausemenu.")
X(BOOL, debug_pick_twice, 0, "Debug trace: pick twice.")
X(BOOL, debug_pick_view, 0, "Debug trace: pick view.")
X(BOOL, debug_print, 1, "Show the game's own debug_print() messages (--debug-print=0 silences them).")
X(BOOL, debug_ramp, 0, "Debug trace: ramp.")
X(BOOL, debug_raster, 0, "Debug trace: raster.")
X(BOOL, debug_recordtick, 0, "Debug trace: recordtick.")
X(BOOL, debug_savedesc, 0, "Debug trace: savedesc.")
X(BOOL, debug_sprpos, 0, "Debug trace: sprpos.")
X(BOOL, debug_stepheight, 0, "Debug trace: stepheight.")
X(BOOL, debug_string_cache, 0, "Debug trace: string cache.")
X(BOOL, debug_talk_twice, 0, "Debug trace: talk twice.")
X(BOOL, debug_texids, 0, "Debug trace: texids.")
X(BOOL, debug_texture_arena, 0, "Debug trace: texture arena.")
X(BOOL, debug_throw, 0, "Debug trace: throw.")
X(INT, debug_timelapse, 0, "Save a screenshot every N ms (1 = 250 ms); 0 disables.")
X(BOOL, debug_titlemenu, 0, "Debug trace: titlemenu.")
X(BOOL, debug_w20, 0, "Debug trace: w20.")
X(BOOL, debug_wall, 0, "Debug trace: wall.")
X(BOOL, debug_weight, 0, "Debug trace: weight.")
X(INT, decal_push, UW_OPT_UNSET, "Decal push-out magnitude (calibration).")
X(INT, decal_push_sign, 1, "Decal push-out sign (calibration).")
X(INT, demo_delay_ms, UW_OPT_UNSET, "Milliseconds between demo script lines (0 = one per pump).")
X(STR, demo_file, NULL, "Play back this demo script (see the demo_*.txt files).")
X(BOOL, demo_keep_running, 0, "Keep the game running after the demo script ends.")
X(BOOL, diag_sprlist, 0, "Diagnostics: sprlist.")
X(BOOL, diag_text, 0, "Diagnostics: text.")
X(BOOL, disable_3d_geometry, 0, "Disable 3d geometry.")
X(BOOL, disable_3d_objects, 0, "Disable 3d objects.")
X(BOOL, disable_pick_rerender, 0, "Disable pick rerender.")
X(BOOL, disable_tile_features, 0, "Disable tile features.")
X(BOOL, dither, 1, "Ordered dithering of dungeon lighting (--dither=0 disables).")
X(STR, dos_data_dir, NULL, "Directory of the DOS version's data, used by --audio-mode=dos|hybrid for its music and effects.")
X(INT, dos_music_volume, 80, "DOS music volume, 0-100.")
X(BOOL, dump_all_objects, 0, "Debug: dump all objects.")
X(STR, dump_containers_file, NULL, "File the container census is written to.")
X(STR, dump_critter_sheet, NULL, "Comma list of critter types to dump as sprite sheets.")
X(INT, dump_critter_sheet_maxdir, 63, "Highest direction swept by --dump-critter-sheet.")
X(INT, dump_critter_sheet_maxframe, 15, "Highest frame swept by --dump-critter-sheet.")
X(BOOL, dump_model_raw, 0, "Debug: dump model raw.")
X(BOOL, dump_names, 0, "Debug: dump names.")
X(BOOL, dump_objects, 0, "Debug: dump objects.")
X(STR, dump_objects_file, NULL, "File the --dump-objects census is written to.")
X(STR, dump_sprite_dir, NULL, "Directory sprite dumps are written to.")
X(STR, dump_sprite_frames, NULL, "Frame ids/ranges (\"5,10-20\") to dump as standalone sprite images.")
X(STR, dump_sprite_ids, NULL, "Object-sprite ids/ranges to dump as standalone sprite images.")
X(BOOL, fast_sleep, 0, "Make Sleep() return immediately (used by the regression runner).")
X(INT, force_critter_frame, UW_OPT_UNSET, "Force every critter to this animation frame.")
X(INT, force_critter_state, UW_OPT_UNSET, "Force every critter into this animation state.")
X(BOOL, fullbright, 1, "Skip the ARM distance falloff for palette indices LIGHT.DAT leaves fullbright (lava, magic).")
X(INT, hack_pitch, UW_OPT_UNSET, "Force the camera pitch (0-360).")
X(BOOL, hack_reveal_depth, 0, "Hack reveal depth.")
X(BOOL, hack_reveal_depth_zero, 0, "Hack reveal depth zero.")
X(STR, light_mode, NULL, "Lighting: \"dos\" uses LIGHT.DAT/SHADES.DAT shade tables; unset/\"arm\" keeps the Pocket PC RGB falloff.")
X(INT, look_slot, UW_OPT_UNSET, "Dump object-slot details for this slot once.")
X(BOOL, model_no_depth_sort, 0, "Model no depth sort.")
X(BOOL, no_force_3d_redraw, 0, "Do not force 3d redraw every pass.")
X(BOOL, no_force_cursor_redraw, 0, "Do not force cursor redraw every pass.")
X(BOOL, no_force_swing_tick, 0, "Do not force swing tick every pass.")
X(INT, palette_cycle_ms, 250, "Milliseconds per water/lava palette-cycle step (0 disables the cycling).")
X(BOOL, pick_diag, 0, "Pick diag.")
X(INT, pick_force_slot, UW_OPT_UNSET, "Force the object-pick pass to this slot.")
X(BOOL, player_no_bounce, 1, "Clear the player's downward velocity on landing (--player-no-bounce=0 restores the bounce).")
X(BOOL, quiet_posdebug, 0, "Quiet posdebug.")
X(INT, record_delay_ms, UW_OPT_UNSET, "DELAY line written into a recorded demo file.")
X(STR, record_demofile, NULL, "Record input to this demo script file.")
X(BOOL, touchscreen, 0, "Use the full-height touchscreen window layout.")
X(INT, turn_accel, 0x60, "Turn acceleration used for keyboard turning.")
X(INT, walk_accel, 0x30, "Walk acceleration used for keyboard movement.")
