#ifndef ORDINAL_STUBS_H
#define ORDINAL_STUBS_H

/* ordint_divmod's return: both halves of one ARM soft-division, named
 * instead of relying on a second, nonexistent "return value" read back
 * from a leftover register (see ordint_divmod's own comment). */
typedef struct {
    int quot;
    int rem;
} divmod_result;

void uw_pump_events();

long EnterCriticalSection(long critical_section, long arg2, long arg3, long arg4);
long GetSystemTime(long system_time);
long LocalAlloc(long flags, long byte_count);
long LocalReAlloc(long block, long byte_count, long flags);
long LocalSize(long block);
long RemoteLocalReAlloc(long arg1, long arg2, long arg3, long arg4, long arg5);
long HeapReAlloc(long heap);
long ce_wcscat();
long ce_wcscpy(char *destination, const char *source);
long ce_wcslen();
long Random();
long SystemParametersInfoW(unsigned int action, unsigned int cb, void *buf, unsigned int fWinIni);
long RegisterClassW(long window_class);
long CopyRect(long rect);
long CreateDirectoryW(long path, long security);
long RemoveDirectoryW();
long CopyFileW(const char *source, const char *destination, int fail_if_exists);
long create_directory_path();
long FindFirstFileW();
long CreateFileW(long path, long access, long share_mode, long security, long creation, long attributes, long template_file);
long ReadFile(long file, long buffer, long byte_count, long bytes_read, long overlapped);
long WriteFile();
long GetFileSize(int handle, unsigned int *high);
long SetFilePointer();
long SetFileTime(long file, long file_time);
long FindNextFileW();
int GetDiskFreeSpaceExW(void *path, unsigned int flags, void *out_struct, unsigned int *out_free_lo);
long MultiByteToWideChar(unsigned int code_page, unsigned int flags, const char *source, int source_count, char *destination, int capacity);
long WideCharToMultiByte(long code_page, long flags, long source, long source_count, long destination, long capacity, long default_char, long used_default);
long GetUserDefaultLangID(long arg1);
long FoldStringW(long string);
long _wcsicmp(unsigned short *a, unsigned short *b);
long CloseAllFileHandles(long arg1);
void *CreateWindowExW(void *a, void *b, void *c, unsigned int d);
long DefWindowProcW();
long ShowWindow(long window, long show_command);
long UpdateWindow(long window);
int FindWindowW(void *a, void *b);
long BatteryDrvrGetLevels(long levels);
long CeReadRecordProps(long arg1, long arg2);
long waveOutClose();
long waveOutPrepareHeader(long wave_out, long header, long header_size);
long waveOutUnprepareHeader(long wave_out, long header, long header_size);
long waveOutWrite(long wave_out, long header, long header_size);
long waveOutReset();
long waveOutOpen(long wave_out, long device_id, long format, long callback, long instance, long flags);
long RegCloseKey(long key);
long RegCreateKeyExW(long key, long sub_key, long reserved, long class_name, long options, long access, long security, long result, long disposition);
int RegOpenKeyExW(unsigned int hkey, void *subkey, unsigned int reserved, void *result);
long RegQueryValueExW(long key, long value_name, long reserved, long type, long data, long data_size);
long RegSetValueExW(long key, long value_name, long reserved, long type, long data, long data_size);
long Sleep();
long GetLastError();
long FindResourceW(long module, long resource_id, long resource_type);
long LoadResource(long resource);
long GetTickCount();
long CloseHandle(int handle);
long GetDlgItemTextW(long dialog, long item_id, long text, long max_count);
long DialogBoxIndirectParamW();
long EndDialog(long dialog, long result);
long SetForegroundWindow(long window);
long ce_sprintf();
long MessageBoxW(long text, long caption);
long DispatchMessageW(long message);
int PeekMessageW(void *msg, void *hwndFilter, unsigned int wMsgFilterMin, unsigned int wMsgFilterMax, unsigned int wRemoveMsg);
long PostQuitMessage(long exit_code);
int PostMessageW(void *hwnd, unsigned int msg, unsigned int wparam, int lparam);
long TranslateMessage(long message);
long GetSystemMetrics(long index);
long DeleteObject(long object);
long GetStockObject(long object_id);
long ce_atoi(long text);
long ordfloat_cos(unsigned long long x);
void LocalFree(void *ptr);
long _itoa(long value, long buffer, long radix);
long ordfloat_log();
long _ltoa(long value, long buffer, long radix);
void *ce_malloc(unsigned int size);
void *ce_memmove(void *dest, void *src, unsigned int n);
void *ce_memset(void *ptr, int val, unsigned int n);
long ce_rand();
void *ce_realloc(void *ptr, unsigned int size);
long ordfloat_sin(unsigned int lo, unsigned int hi);
long ce_srand(long seed);
char *ce_strcat(char *dest, char *src);
char *ce_strchr(const char *s, int c);
int ce_strcmp(const char *a, const char *b);
unsigned int ce_strlen(const char *s);
int ce_strncmp(const char *a, const char *b, unsigned int n);
long ce_strncpy(char *dest, const char *src, unsigned int n);
long ce_strstr(long haystack, long needle);
long ce_tolower(long ch);
long ce_toupper(long ch);
long cpp_operator_delete(long block);
long cpp_operator_new(long byte_count);
void NKDbgPrintfW(const char *fmt, ...);
void *ce_fopen(void *path, void *mode);
int ce_fscanf(void *f, const char *fmt, ...);
int ce_fclose(void *f);
void *ce_calloc(unsigned int elem_size, unsigned int count);
long ce_strrchr(char *str, int c);
long _strlwr(long text);
long _strupr(char *str);
long _isctype(int c, int mask);
divmod_result ordint_divmod(int divisor, int dividend);
divmod_result orduint_divmod(unsigned int divisor, unsigned int dividend);
long ordfloat_sub(unsigned int a, unsigned int b);
long ordfloat_double_binop(long a_lo, long a_hi, long b_lo, long b_hi);
long ordfloat_int_to_float(unsigned int x);
long ordfloat_uint_to_float(unsigned int x);
long ordfloat_float_to_double(unsigned long long x);
long ordfloat_negate(unsigned int x);
long ordfloat_mul(unsigned int a, unsigned int b);
long ordfloat_double_mul2(unsigned int alo, unsigned int ahi, unsigned int blo, unsigned int bhi);
long ordfloat_lt(unsigned int a, unsigned int b);
long ordfloat_le(unsigned int a, unsigned int b);
long ordfloat_int_to_float2(int x);
long ordfloat_double_from_int(long value);
long ordfloat_gt(unsigned int a, unsigned int b);
long ordfloat_ge(unsigned int a, unsigned int b);
long ordfloat_double_to_float(unsigned long long x);
long ordfloat_double_result();
long ordfloat_div(unsigned int a, unsigned int b);
long ordfloat_double_binop2(long a_lo, long a_hi, long b_lo, long b_hi);
long ordfloat_add(unsigned int a, unsigned int b);
long ordfloat_double_op3(long a_lo, long a_hi, long b_lo, long b_hi);
long ordaudio_op_2063(long arg1, long arg2, long arg3, long arg4);
long ordaudio_op_2135();
long ordaudio_op_2142(long arg1);
long ordaudio_op_2304(long arg1, long arg2, long arg3);
long ordaudio_op_2413(long arg1, long arg2, long arg3);
long ordaudio_op_2582();
long ordaudio_op_2588(long archive, long value);

#endif
