#ifndef ORDINAL_STUBS_H
#define ORDINAL_STUBS_H

/* ordint_divmod's return: both halves of one ARM soft-division, named
 * instead of relying on a second, nonexistent "return value" read back
 * from a leftover register (see ordint_divmod's own comment). */
typedef struct {
    int quot;
    int rem;
} divmod_result;

void uw_pump_events(void);

long EnterCriticalSection();
long GetSystemTime();
long LocalAlloc();
long LocalReAlloc();
long LocalSize();
long RemoteLocalReAlloc();
long HeapReAlloc();
long ce_wcscat();
long ce_wcscpy();
long ce_wcslen();
long Random();
long SystemParametersInfoW();
long RegisterClassW();
long CopyRect();
long CreateDirectoryW();
long RemoveDirectoryW();
long CopyFileW();
long create_directory_path();
long FindFirstFileW();
long CreateFileW();
long ReadFile();
long WriteFile();
long GetFileSize(int handle, unsigned int *high);
long SetFilePointer();
long SetFileTime();
long FindNextFileW();
int GetDiskFreeSpaceExW(void *path, unsigned int flags, void *out_struct, unsigned int *out_free_lo);
long MultiByteToWideChar();
long WideCharToMultiByte();
long GetUserDefaultLangID();
long FoldStringW();
long _wcsicmp();
long CloseAllFileHandles();
void *CreateWindowExW(void *a, void *b, void *c, unsigned int d);
long DefWindowProcW();
long ShowWindow();
long UpdateWindow();
int FindWindowW(void *a, void *b);
long BatteryDrvrGetLevels();
long CeReadRecordProps();
long waveOutClose();
long waveOutPrepareHeader();
long waveOutUnprepareHeader();
long waveOutWrite();
long waveOutReset();
long waveOutOpen();
long RegCloseKey();
long RegCreateKeyExW();
int RegOpenKeyExW(unsigned int hkey, void *subkey, unsigned int reserved, void *result);
long RegQueryValueExW();
long RegSetValueExW();
long Sleep();
long GetLastError();
long FindResourceW();
long LoadResource();
long GetTickCount();
long CloseHandle();
long GetDlgItemTextW();
long DialogBoxIndirectParamW();
long EndDialog();
long SetForegroundWindow();
long ce_sprintf();
long MessageBoxW();
long DispatchMessageW();
int PeekMessageW(void *msg, void *hwndFilter, unsigned int wMsgFilterMin, unsigned int wMsgFilterMax, unsigned int wRemoveMsg);
long PostQuitMessage();
int PostMessageW(void *hwnd, unsigned int msg, unsigned int wparam, int lparam);
long TranslateMessage();
long GetSystemMetrics();
long DeleteObject();
long GetStockObject();
long ce_atoi();
long ordfloat_cos();
void LocalFree();
long _itoa();
long ordfloat_log();
long _ltoa();
void *ce_malloc();
void *ce_memmove();
void *ce_memset(void *ptr, int val, unsigned int n);
long ce_rand();
void *ce_realloc(void *ptr, unsigned int size);
long ordfloat_sin();
long ce_srand();
char *ce_strcat();
char *ce_strchr(const char *s, int c);
int ce_strcmp(const char *a, const char *b);
unsigned int ce_strlen();
int ce_strncmp(const char *a, const char *b, unsigned int n);
long ce_strncpy();
long ce_strstr();
long ce_tolower();
long ce_toupper();
long cpp_operator_delete();
long cpp_operator_new();
void NKDbgPrintfW(const char *fmt, ...);
void *ce_fopen(void *path, void *mode);
int ce_fscanf(void *f, const char *fmt, ...);
int ce_fclose(void *f);
void *ce_calloc();
long ce_strrchr();
long _strlwr();
long _strupr();
long _isctype();
divmod_result ordint_divmod();
divmod_result orduint_divmod();
long ordfloat_sub();
long ordfloat_double_binop();
long ordfloat_int_to_float();
long ordfloat_uint_to_float();
long ordfloat_float_to_double();
long ordfloat_negate();
long ordfloat_mul();
long ordfloat_double_mul2();
long ordfloat_lt();
long ordfloat_le();
long ordfloat_int_to_float2();
long ordfloat_double_from_int();
long ordfloat_gt();
long ordfloat_ge();
long ordfloat_double_to_float();
long ordfloat_double_result();
long ordfloat_div();
long ordfloat_double_binop2();
long ordfloat_add();
long ordfloat_double_op3();
long ordaudio_op_2063();
long ordaudio_op_2135();
long ordaudio_op_2142();
long ordaudio_op_2304();
long ordaudio_op_2413();
long ordaudio_op_2582();
long ordaudio_op_2588();

#endif
