#ifndef UW_TEST_TRANSITIONS_FIXTURE_H
#define UW_TEST_TRANSITIONS_FIXTURE_H
#include "unity.h"
#include "src/headers/debug.h"
#include "src/headers/file_io.h"
#include "../transitions_test_globals.h"
undefined4 babl_render_op_wrap_message(void);
undefined4 babl_render_op_say(void);
undefined4 babl_render_op_play_sound(void);
void *ce_malloc(unsigned int count);
void *ce_calloc(unsigned int count, unsigned int size);
void *ce_memset(void *p, int value, unsigned int count);
void *ce_memmove(void *p, const void *source, unsigned int count);
char *ce_strcat(char *p, const char *source);
void LocalFree(void *p);
long CloseHandle(int handle);
long Sleep(unsigned int ms);
int open_file_for_read(const char *path);
int read_file_handle(int handle, void *p, unsigned int count);
int seek_file_handle(int handle, int offset, int origin);
uint read_realtime_clock_units(void);
long GetTickCount(void);
long TranslateMessage(void);
long DispatchMessageW(void);
long _isctype(int key, int mask);
long ce_tolower(int key);
long ce_toupper(int key);
int PeekMessageW(void *msg, void *hwnd, unsigned int low,
                unsigned int high, unsigned int remove);
void noop_key_handler(void);
void update_mouse_state(void);
void debug_framebuffer_dump(const char *tag);
void apply_palette_buffer(void *palette, int flag);
void tick_book_illustration_palette_cycles(ushort *cycle_record);
void clear_ambient_sound_target(void);
void voice_sample_cluster_stub_1(void);
void voice_sample_cluster_stub_2(void);
void advance_menu_music_track(void);
void stop_voice_sample(void);
void clear_screen_and_restore_cursor(void);
void thunk_FUN_0007ec1c(void);
void draw_text_string(char *text, short x, short y);
int measure_text_width(char *text);
undefined4 get_audio_subsystem_flag(void);
undefined4 play_numbered_voice_sample(void);
bool is_voice_sample_finished(void);
undefined4 play_music_track(void);
bool select_active_font(char *font_filename);
bool set_palette_bank(void);
void decrement_cursor_hide_depth(void);
void load_dungeon_texture_arenas(void);
void change_game_mode(void);
undefined4 cursor_show_idle_tick(void);
void *GXBeginDraw(void);
int GXEndDraw(void);
void assert_visible_picture(void);
void render_dungeon_frame_timed(void);
undefined4 dungeon_view_anim_tick(void);
void refresh_equipment_display_if_visible(void);
void handle_game_victory_sequence(void);
void movement_pacing_handler(void);
void sync_player_stats_to_hud(void);
void hud_panel_redraw_dispatch(void);
void enter_automap_screen(void);
void exit_automap_screen(void);
void enter_conversation_mode_screen(void);
void exit_talk_mode(void);
void transitions_fixture_reset(void);
void transitions_fixture_dispose(void);
int uw_always_show_cursor(void);
void clear_ambient_sound_target_thunk(void);
char *chrbtns_bump_alloc_entry(int size);
int chrbtns_offset_table_builder(int index, int kind, int entry);

void dirty_rect_set(int top, int bottom, int left, int right);
void dispatch_sticky_mode_handlers(void);
void uw_debug_blit_pick_buffer(void);
void render_dungeon_view_frame(void);
void uw_debug_draw_inv_hotspot_positions(void);
void dbgui_draw(void);
char *LAB_000255b4(void);
undefined4 LAB_000255d0(void);
uint load_gr_resource_entries(void);
undefined4 reset_dialogue_speech_state(void);
void chargen_ui_transition_hook(int is_press);
void init_new_character_record(int mode);
void report_fatal_error_and_exit(void);
void set_viewport_clip_rect(short left, short top, short right, short bottom);
bool read_buffer_from_file(char *path, void *buffer, unsigned int count);
bool load_pals_bank(unsigned int bank, void *buffer);
int character_generator_loop(char *tree_data, char *scratch_data, char *field_records);
void unregister_game_view_interact_zones(void);
void configure_dungeon_viewport(int x, int y, int width, int height);
void enter_dungeon_view_hud_init(void);
void refresh_player_equipment_effects(void);
void full_dungeon_redraw(void);
void weapon_overlay_and_full_redraw(void);
void enter_pause_menu_state(int state);
void get_mouse_position(void);
void handle_pause_menu_region_click(void);
void handle_pause_menu_dpad_navigation(void);
void close_ui_panel_return_to_game(void);
void select_msg_scroll_mode_normal(void);
int message_scroll_print_wrapped(void);
void set_draw_color(short color_index);
void rect_fill_or_save_restore(ushort left, uint top, short right, short bottom);
void uw_debug_dump_sprite_frames_once(void);
void uw_debug_dump_critter_sheet_once(void);
void uw_debug_force_item_id_once(void);
void tick_weapon_swing_state(short attack_direction);
void poll_input_bindings(undefined1 *input_state);
#endif
